version: '3'

services:
 web:
   container_name: react_scroll
   image: nginx:1.15-alpine
   volumes:
     - './dist/:/usr/share/nginx/html'
     - './nginx.conf:/etc/nginx/nginx.conf'
   ports:
     - '3000:80'